### ISSUE TITLE
Best way to Sniff the Cookie

### ISSUE THREAD

**Issue by HaxXorHardy** [dank/tarkov#16]
what is the best way to sniff the `PHPSESSID` cookie. idk how to find it. I tried wireshark but with no success. 
I'm sorry if this annoys you.

**Comment by dank** [comment]
It's impossible to sniff HTTPS traffic with Wireshark because that's the reason HTTPS was created.

Use [Fiddler](https://www.telerik.com/fiddler) or [Charles Proxy](https://www.charlesproxy.com/), they will generated a Root Certificate to allow HTTPS sniffing. Although there are some limitations, you should be able to get the cookie at least.

**Comment by HaxXorHardy** [comment]
i can't get it to run. every time I start Fiddler then EFT disconnects. maybe you have a tip for me?

**Comment by dank** [comment]
EFT doesn’t let you sniff traffic because it has a security feature called SSL pinning. You can still grab the session cookie, look harder.

**Comment by HaxXorHardy** [comment]
sorry i tryed for 1h now. please help me. :(

**Comment by MartyEz** [comment]
> It's impossible to sniff HTTPS traffic with Wireshark because that's the reason HTTPS was created.
> 
> Use [Fiddler](https://www.telerik.com/fiddler) or [Charles Proxy](https://www.charlesproxy.com/), they will generated a Root Certificate to allow HTTPS sniffing. Although there are some limitations, you should be able to get the cookie at least.

Your device is able to decrypt traffic and you can get the shared secret of the tls session with wireshark
